upstream web {
    # zone: estado do round-robin compartilhado entre os workers do nginx
    zone web 64k;
    server web-01:80;
    server web-02:80;
    server web-03:80;
    server web-04:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://web;
        add_header Cache-Control "no-store";
        add_header X-Served-By $upstream_addr;
    }
}
